### ISSUE TITLE
Update chalk dependency

### ISSUE THREAD

**Issue by segrey** [shakyShane/tfunk#5]
At the moment `"chalk": "^0.5.1"` is being targeted.
Please update this dependency to "1.0" or higher, because these versions contain different improvements https://github.com/chalk/chalk/releases/tag/v1.0.0. One of them is a possibility to force enable color support for processes launched without tty (for example Node.js apps launched from IDE).

**Comment by shakyShane** [comment]
Please send a PR and I will happily accept :)
